export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ERRORS = 'SET_ERRORS';

export const MYPAGE_SET_USER = 'MYPAGE_SET_USER';
export const MYPAGE_SET_CAFES = 'MYPAGE_SET_CAFES';
export const MYPAGE_DELETE_CAFE = 'MYPAGE_DELETE_CAFE';
export const MYPAGE_SET_REVIEWS = 'MYPAGE_SET_REVIEWS';
export const MYPAGE_SET_RATES = 'MYPAGE_SET_RATES';
export const MYPAGE_CLEAR = 'MYPAGE_CLEAR';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const MYPAGE_SET_LOADING_CAFE = 'MYPAGE_SET_LOADING_CAFE';
export const MYPAGE_SET_LOADING_REVIEW = 'MYPAGE_SET_LOADING_REVIEW';
export const MYPAGE_SET_LOADING_RATE = 'MYPAGE_SET_LOADING_RATE';

export const EDIT_USER_PHOTO = 'EDIT_USER_PHOTO';
export const DELETE_USER_PHOTO = 'DELETE_USER_PHOTO';
export const USER_PHOTO_UPLOADING = 'USER_PHOTO_UPLOADING';

export const PHOTO_SET_UPLOADING = 'PHOTO_SET_UPLOADING';
export const PHOTO_SET_COUNT = 'PHOTO_SET_COUNT';

export const GARELLY_CLEAR_PHOTOS = 'GARELLY_CLEAR_PHOTOS';
export const GARELLY_ADD_PHOTOS = 'GARELLY_ADD_PHOTOS';
export const GARELLY_SET_LOADING = 'GARELLY_SET_LOADING';
export const GARELLY_SET_COMPLETE = 'GARELLY_SET_COMPLETE';

export const SET_NEW_CAFES = 'SET_NEW_CAFES';
export const CAFE_SET_LOADING = 'CAFE_SET_LOADING';
export const UPDATE_CAFE = 'UPDATE_CAFE';
export const UPDATE_CAFE_PHOTO = 'UPDATE_CAFE_PHOTO';
export const EDIT_CAFE_PHOTO = 'EDIT_CAFE_PHOTO';
export const DELETE_CAFE_PHOTO = 'DELETE_CAFE_PHOTO';
export const SEARCH_CAFES = 'SEARCH_CAFES';
export const SET_CAFES = 'SET_CAFES';
export const SET_CAFE_DETAILS = 'SET_CAFE_DETAILS';

export const SET_NEW_REVIEWS = 'SET_NEW_REVIEWS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';